/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author AA
 */
public class addempform_form1 extends javax.swing.JFrame {
    
    int y=0;
    int z=0;
    int x=0;
    int w=0;
    
    static Connection con45;
    public static void connect() throws ClassNotFoundException, SQLException
    {
        try
        {
        Class.forName("com.mysql.jdbc.Driver");
		String url="jdbc:mysql://localhost:3306/employee";
		String user="root";
		String pass="monil";
		con45=DriverManager.getConnection(url,user,pass);
    }
    catch(Exception e){}}

    /**
     * Creates new form addempform_form1
     */
    public addempform_form1() {
        initComponents();
        this.setTitle("ADD EMPLOYEE");
        b.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        e = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        d = new javax.swing.JComboBox();
        f = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("ADD EMPLOYEE");

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Employee No:-");

        b.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bFocusLost(evt);
            }
        });
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Employee Name:-");

        c.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cFocusLost(evt);
            }
        });
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Employee Designation:-");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Employee Salary:-");

        e.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                eFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Employee Department:-");

        insert.setText("INSERT RECORD");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        d.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Designation>", "DIRECTOR", "CEO", "CTO", "DBA", "MANAGER", "CFO", "SALES MAN", "ASSISTANT MANAGER", "JANITOR", " " }));
        d.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dFocusLost(evt);
            }
        });

        f.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Department>", "HR", "PRODUCTION", "R&D", "MANAGEMENT", "TECHNICAL", "FINANCE" }));
        f.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fFocusLost(evt);
            }
        });
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(back)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clear))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(c)
                                .addComponent(b)
                                .addComponent(e)
                                .addComponent(d, 0, 152, Short.MAX_VALUE)
                                .addComponent(f, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear)
                    .addComponent(back))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insert, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        this.dispose();

        new form1().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed

                b.setText("");
                c.setText("");
                d.setSelectedIndex(0);
                e.setText("");
                f.setSelectedIndex(0);
                b.grabFocus();

        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed

        
            
        try
        {
            
              String p1=b.getText();
              String q1=c.getText();
              String r1=d.getSelectedItem().toString();
              String s1= e.getText();
              String t1=f.getSelectedItem().toString();
              
             
                 //main program for add employee
                 connect();
                 int n=0,l=0;
                 int k=Integer.parseInt(b.getText());
                 java.sql.PreparedStatement pst2=con45.prepareStatement("select * from emp");
                 ResultSet rst=pst2.executeQuery();
        while(rst.next())
        {
            n=Integer.parseInt(rst.getString(1));
            if(n==k)
            {
                l=1;
                break;
            }
            
        }
        if(l==1)
        {
             JOptionPane.showMessageDialog(this,"Employee No. Already Exist");
             b.setText("");
             b.grabFocus();
        }
        else
        {
            int y=0;
            int p=Integer.parseInt(b.getText());
            String q=c.getText();
            String r=d.getSelectedItem().toString();
            int s= Integer.parseInt(e.getText());
            String t=f.getSelectedItem().toString();
            java.sql.PreparedStatement pst=con45.prepareStatement("INSERT INTO emp (empno, ename, designation, salary, department) VALUES (?,?,?,?,?)");
            pst.setInt(1,p);
            pst.setString(2, q);
            pst.setString(3, r);
            pst.setInt(4, s);
            pst.setString(5, t);
            y=pst.executeUpdate();
            if(y==0)
            {
                JOptionPane.showMessageDialog(this,"Data Feeding Failed");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Data Successfully Entered");
                b.setText("");
                c.setText("");
                d.setSelectedIndex(0);
                e.setText("");
                f.setSelectedIndex(0);
                b.grabFocus();
            }
        }
        }
        
        catch(Exception e){}

        // TODO add your handling code here:
    }//GEN-LAST:event_insertActionPerformed

    private void cFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cFocusLost
 
        if(y!=1)
        {
        String q1=c.getText();
        int flag=0;
        for(int j=0;j<q1.length();j++)
            {
                if((Character.isDigit(q1.charAt(j))))
                {
                    flag=1;
                    break;
                } 
            }
         if(q1.equals(""))
              {
               z=1;
               JOptionPane.showMessageDialog(this,"Employee name can't be left blank"); 
               c.grabFocus();
              }
        
         else if(flag==1)
         {
             c.setText(""); 
             z=1;
             JOptionPane.showMessageDialog(this,"Employee name can't have digits"); 
             c.grabFocus();
              
         }
         
         else
         {
         z=0;
         }
        }
       
    }//GEN-LAST:event_cFocusLost

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fActionPerformed

    private void dFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dFocusLost

        if((z!=1)&&(y!=1))
        {
            String hh=d.getSelectedItem().toString();
            if(hh.equals("<Designation>"))
            {
                x=1;
                JOptionPane.showMessageDialog(this,"Select the designation"); 
                d.grabFocus();
            }
            else
            {
                x=0;
            }
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_dFocusLost

    private void eFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eFocusLost

          String p1=e.getText();
          int flag=0;
         if((y!=1)&&(z!=1)&&(x!=1))
         {
          for(int j=0;j<p1.length();j++)
            {
                if(!(Character.isDigit(p1.charAt(j))))
                {
                    flag=1;
                    break;
                }
                
            }
         if(p1.equals(""))
                      {
                          w=1;
                          JOptionPane.showMessageDialog(this,"Employee No. can't be empty");
                          e.grabFocus();   
                      }
         else if(flag==1)
                 {
                      w=1;
                      JOptionPane.showMessageDialog(this,"Employee No. should be numeric only");
                      e.setText("");
                      e.grabFocus();
                 }
         else
         {
             w=0;
         }
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_eFocusLost

    private void fFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fFocusLost

         if((z!=1)&&(y!=1)&&(x!=1)&&(w!=1))
        {
            String hh=f.getSelectedItem().toString();
            if(hh.equals("<Department>"))
            {
                
                JOptionPane.showMessageDialog(this,"Select the department"); 
                f.grabFocus();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_fFocusLost

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void bFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bFocusLost

        String p1=b.getText();
        int flag=0;
        for(int j=0;j<p1.length();j++)
        {
            if(!(Character.isDigit(p1.charAt(j))))
            {
                flag=1;
                break;
            }

        }
        if(p1.equals(""))
        {
            y=1;
            JOptionPane.showMessageDialog(this,"Employee No. can't be empty");
            b.grabFocus();

        }
        else if(flag==1)
        {
            y=1;
            JOptionPane.showMessageDialog(this,"Employee No. should be numeric only");

            b.setText("");
            b.grabFocus();

        }
        else
        {
            y=0;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addempform_form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addempform_form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addempform_form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addempform_form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addempform_form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b;
    private javax.swing.JButton back;
    private javax.swing.JTextField c;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox d;
    private javax.swing.JTextField e;
    private javax.swing.JComboBox f;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
